apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-01-21T05:25:29Z"
  generation: 2
  labels:
    app: nodejstest
  name: nodejstest
  namespace: default
  resourceVersion: "10653"
  selfLink: /apis/apps/v1/namespaces/default/deployments/nodejstest
  uid: 613e7f7b-feb5-4f36-b87f-e47f08701e24
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nodejstest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejstest
    spec:
      containers:
        - image: gcr.io/cogteach-distributed/github.com/voivio/gazelearning@sha256:425b8da6c0f4c9b1462e7e6a5e02cdda6baa0bb6277e2e40d49a8739d0135f6c
          imagePullPolicy: IfNotPresent
          name: gazelearning-sha256-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2021-01-21T05:26:16Z"
      lastUpdateTime: "2021-01-21T05:26:16Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-01-21T05:25:29Z"
      lastUpdateTime: "2021-01-21T05:26:16Z"
      message: ReplicaSet "nodejstest-66cd49cbf6" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
