apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejstest
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: gcr.io/gazelearningdemo/github.com/voivio/gazelearning:$COMMIT_SHA
          ports:
            - containerPort: 5000
