apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python
  name: python
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - image: gcr.io/cogteach-distributed/github_voivio_gazelearning/python
          imagePullPolicy: IfNotPresent
          name: gazelearning-sha256-1
          volumeMounts:
          - mountPath: /mnt/fileserver
            name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: fileserver-claim
          readOnly: false
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: python
  name: python-hpa-rpvo
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python
---
apiVersion: v1
kind: Service
metadata:
  name: python-nodeport-service
  namespace: default
spec:
  selector:
    app: python
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
# apiVersion: v1
# kind: Service
# metadata:
#   name: python-nodeport-service
#   namespace: default
# spec:
#   clusterIP: 10.52.1.89
#   externalTrafficPolicy: Cluster
#   ports:
#     - nodePort: 31721
#       port: 85
#       protocol: TCP
#       targetPort: 8000
#   selector:
#     app: python
#   sessionAffinity: None
#   type: NodePort
