apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dedicated-python
  name: dedicated-python
  namespace: default
spec:
  selector:
    matchLabels:
      app: dedicated-python
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dedicated-python
    spec:
      containers:
        - image: gcr.io/cogteach-distributed/github_voivio_gazelearning/python
          imagePullPolicy: IfNotPresent
          name: gazelearning-sha256-1
          # Default command for container to run is node server.js
          command: [ "python" ]
          args: [ "dedicated_server.py" ]
          volumeMounts:
            - mountPath: /mnt/fileserver
              name: mypvc
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: fileserver-claim
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: dedicated-python-nodeport-service
  namespace: default
spec:
  selector:
    app: dedicated-python
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000